language: ruby
rvm:
- 2.3.1
env:
- DB=postgresql
script:
- rails spec
before_script:
- rails db:create RAILS_ENV=test
- rails db:migrate
bundler_args: "--binstubs=./bundler_stubs"
deploy:
  provider: heroku
  app: dbz-feedback
  api_key:
    secure: HMr94t0keu8TactXR58FonHdXQVQt95UbLyuONxrlC7NwluEM5MZNtQflGedtAGxJKfRspKm0RLCSw+0O+3c5ABrRUerAKDE+EONlpI9M56IA+iAXPhPFgXW1SVXNznVqvYmiTmGnrooYYA/5oI2eSWzGi2k9j5I3uG5zcdyMiUii8CfGmyjV9niWV3r+Xkg7QaCkYQ28M4p64WZpN2aVGgmM8GzTb2lgeeiH1jfAZBvVTYhFY/AvhhQANSmo+i85qHPNyzZZCZYbEdu+Wrrd+jmpBC7aEXr2mX+F0JUmHH06jfFFN7JpfmHTDkh+NC8xFi5vRAlNBKQ8wpewmHVOdoAAoqHTK5+g3KQVT9DYJcu5kTV8t2iFyMcJzEh7j++cyu7TBixjaciP2zrqN4AAEuQY2ip9j1X1ovO7Icv2/R1AOpar8fsPZLR+MJ1fowfjOEArKUNyoU3YfNVgZSDqlz7RJUMTqJ/mroAy2cxwPXSJOiwkZyaxGlRxttclEUZx2m+B2jwwZ485eZg0kV9auu/+7FOZGwlVyIW/nmJ33LatXpXmtABlrXf4npAM4kxmTFVn+QuGqzWAgOP8liZYmn14PThX8TmiaivKl2DNUrqs21SmPwHf1pw9JNB/a4jVUpakjLKoqqtEs1tqEWQPfbvJdDk8THl9AIkPImcPcE=
